project:
  type: website
  output-dir: docs
  resources:
  - "data/*" 


website:
  title: "interactvie_maps"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Terra Nova"
        href: TN_map.qmd
      - text: "Gros Morne"
        href: GM_map.qmd 

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    page-layout: full

editor: visual
