project:
  type: website
  resources:
  - "data/*" 
  output-dir: docs

website:
  title: "interactvie_maps"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Terra Nova"
        href: TN_map.qmd
      - text: "Gros Morne"
        href: GM_map.qmd 

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
